name: test-pr-creation
on: 
  repository_dispatch: 
    types:
      - echo-payload

jobs:
  echo-payload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '15'
      - run: 'npm install'
      - run: 'node ./pr-creation/index.js'
        with:
          myToken: "${{ secrets.GITHUB_TOKEN }}"

