name: test-pr-creation

on: 
  repository_dispatch: 
    types:
      - echo-payload

jobs:
  echo-payload:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2
      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with: 
          node-version: '15'
      - name: 'NPM Install'
        run: 'npm install'
      - name: 'Create PR'
        run: 'node ./pr-creation/index.js'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
