name: test-pr-creation
on: 
  repository_dispatch: 
    types:
      - echo-payload

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'echo "Stuff: ${{github.event.client_payload}}"'
